name: Continuous Integration Checks

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain: [ stable, beta ]
        include:
          - toolchain: stable
            check-fmt: true
          - toolchain: 1.48.0
            platform: ubuntu-latest
            msrv: true

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
      - name: Pin crates for MSRV
        if: matrix.msrv
        run: |
          # The serde_json crate switched to Rust edition 2021 starting with v1.0.101, i.e., has MSRV of 1.56
          cargo update -p serde_json --precise "1.0.99" --verbose
          cargo update -p serde --precise "1.0.156" --verbose
          # The quote crate switched to Rust edition 2021 starting with v1.0.31, i.e., has MSRV of 1.56
          cargo update -p quote --precise "1.0.30" --verbose
          # The proc-macro2 crate switched to Rust edition 2021 starting with v1.0.66, i.e., has MSRV of 1.56
          cargo update -p proc-macro2 --precise "1.0.65" --verbose
          cargo update -p chrono --precise "0.4.24" --verbose
      - name: Cargo check
        run: cargo check --release
      - name: Check documentation
        run: cargo doc --release
      - name: Build on Rust ${{ matrix.toolchain }}
        run: cargo build --verbose --color always
      - name: Check formatting
        if: matrix.check-fmt
        run: rustup component add rustfmt && cargo fmt --all -- --check
      - name: Test on Rust ${{ matrix.toolchain }}
        run: cargo test
